### ISSUE TITLE
Null safety?

### ISSUE THREAD

**Issue by wiradikusuma** [ch-muhammad-adil/flutter-circular_profile_avatar#10]
Now that Flutter 2 is out, can we please migrate to null-safe?

**Comment by ch-muhammad-adil** [comment]
Yeah I am already planing on it .. Will surely do that as soon as possible.

**Comment by ch-muhammad-adil** [comment]
It is added here 
https://pub.dev/packages/circular_profile_avatar/versions/2.0.1-nullsafety
