### ISSUE TITLE
does this work with Flutter 2.0 web?

### ISSUE THREAD

**Issue by steveny909** [ch-muhammad-adil/flutter-circular_profile_avatar#13]
Now that Flutter 2.0 is out, does anyone know if this package works on web?  pub.dev doesn't have web designation.

**Comment by ch-muhammad-adil** [comment]
Hello, we will add a release in next week. It has already upgraded to 2.0
but I am investigating that why it is still not available for web.

**Comment by ch-muhammad-adil** [comment]
Yes already added support here 
https://pub.dev/packages/circular_profile_avatar/versions/2.0.1-nullsafety 
Let me know if you are able to use it..
