### ISSUE TITLE
There should be an option to display image as it is (without being in a circle)

### ISSUE THREAD

**Issue by arpit24sahu** [ch-muhammad-adil/flutter-circular_profile_avatar#15]
The reason it was required because, if I am using this plugin, I don't want to use any other plugin to cache images, as this works fine.
But if now I need to display the image as-is (and not in a Circular Widget), I have to use another widget, which cannot get the Image from the cache. So an option to programmatically disable the circular widget, would be great.

**Comment by ch-muhammad-adil** [comment]
Hello Arpit,

So you mean the image should be displayed as a square? Well this is
circular profile avatar, I will think about this suggestion as well. Thanks
for reporting.

Regards,
Muhammad Adil
