### ISSUE TITLE
Image is Oval and not Circular

### ISSUE THREAD

**Issue by chemickypes** [ch-muhammad-adil/flutter-circular_profile_avatar#4]
Hi, I used your library but the result image ha an oval shape.

```dart

CircularProfileAvatar(
        state.user.profileImage,
        radius: 18,
        backgroundColor: Colors.transparent,
        borderWidth: 1,
        borderColor: Colors.white,
        cacheImage: true,
        initialsText: Text(
          state.user.name[0],
          style: TextStyle(color: Colors.white, fontSize: 18),
        ),
        onTap: () {
          print("image tap");
          // action();
        },
      );
``` 

I suppose that the problem is caused because the image I used is rectangular.

**Comment by ch-muhammad-adil** [comment]
Hello thanks for reporting issue, I have tried your code and it looks fine here with portrait mode picture. 



```
CircularProfileAvatar(
                'http://www4.pictures.zimbio.com/gi/Lionel+Messi+Argentina+v+Nigeria+Group+B+2010+9LVH1-kOJNGl.jpg',
                radius: 18,
                backgroundColor: Colors.transparent,
                borderWidth: 1,
                borderColor: Colors.white,
                cacheImage: true,
                initialsText: Text(
                  'Messi'[0],
                  style: TextStyle(color: Colors.white, fontSize: 18),
                ),
                onTap: () {
                  print("image tap");
                  // action();
                },
              ),    
```
           
Here are the results it has produced, So far i guess parent widgets of `CircularProfileAvatar` has height/width smaller than what you have given to the `radius*2` of `CircularProfileAvatar`. Providing more information might can help you. Right now i am closing it. 

<img width="208" alt="Screenshot 2019-09-11 at 1 54 45 PM" src="https://user-images.githubusercontent.com/8264639/64682946-ce705b00-d49b-11e9-839e-26c628017d7f.png">
<img width="174" alt="Screenshot 2019-09-11 at 1 55 09 PM" src="https://user-images.githubusercontent.com/8264639/64682948-cf08f180-d49b-11e9-95d7-5cdc92492ecc.png">
