### ISSUE TITLE
Breaks with cached_network_image ^2.0.0-rc

### ISSUE THREAD

**Issue by premy** [ch-muhammad-adil/flutter-circular_profile_avatar#5]
Could you please update?

**Comment by ch-muhammad-adil** [comment]
I have upgraded it with the latest version of `cached_network_image 1.1.3`. Please feel free to report back if you face any issue.  I am using flutter's stable channel and 2.0.0-rc.1 requires Flutter SDK version >=1.10.15-pre.148 <2.0.0

Now latest version of circular_profile_avatar is 1.0.3.

**Comment by ch-muhammad-adil** [comment]
I have upgraded the package to latest flutter version released yesterday. You can now use it with ^2.0.0-rc-1
