### ISSUE TITLE
How to use local images (assets folder) instead remote images?

### ISSUE THREAD

**Issue by wemersonrv** [ch-muhammad-adil/flutter-circular_profile_avatar#6]
Hello.

And about local images located in my `assets/images` folder... is there a way to show them ?

**Comment by ch-muhammad-adil** [comment]
Thank you for bringing it up, I will add some support for it.

**Comment by omarmir** [comment]
Thanks, that would actually be great!

**Comment by ch-muhammad-adil** [comment]
I have added a `child` parameter, you can pass your `AssetImage` to that parameter. Height and width of child widget doesn't matter as `radius` parameter of `CircularProfileAvatar` is taking care of these things. Please update your plugin to `1.0.6`.
