### ISSUE TITLE
Image is being cached event after setting cacheImage property to false.

### ISSUE THREAD

**Issue by ashishkumart** [ch-muhammad-adil/flutter-circular_profile_avatar#7]
I am using it in my application, and the profile picture URL is same always for a user. Issue is the profile picture is not being changed on refresh, even after setting `cacheImage `property to false.

**Comment by ch-muhammad-adil** [comment]
I have tested it by switching between different images from the example app. Widget is working fine. Can you paste your class/code where you are using it and how you are refreshing it. It should work fine for you too.

**Comment by ch-muhammad-adil** [comment]
I am closing this issue, as it is working fine.
