### ISSUE TITLE
I cant add background image

### ISSUE THREAD

**Issue by vipuluthaiah** [ch-muhammad-adil/flutter-circular_profile_avatar#8]
I am trying flutter i tried cloning whatsapp ui ..i needed status page Circular Avator to b custom i cant add[](url)

**Comment by ch-muhammad-adil** [comment]
You can make your own background card and can use this circular profile avatar over it.

**Comment by ch-muhammad-adil** [comment]
Use Stack Widget

**Comment by vipuluthaiah** [comment]
Thank U i will try!!!
https://github.com/vipuluthaiah/Flutter-WhatsApp-Clone-Black/blob/master/screenshot/Screenshot_1583247702.png

i wanted to make this as custom avator!!i will try
