### ISSUE TITLE
Off centre display

### ISSUE THREAD

**Issue by AllanSullivan** [ch-muhammad-adil/flutter-circular_profile_avatar#9]
I've just tried this package out but get an unexpected output, the icon is not centered.
![Screenshot_20200424-114218](https://user-images.githubusercontent.com/63913718/80205707-fa071680-8622-11ea-9506-0551f0fc41d0.jpg)

```
CircularProfileAvatar(
                    null,
                    child: Icon(
                      Icons.account_circle,
                      size: 200.0,
                    ),
                    borderColor: Colors.black,
                    borderWidth: 3,
                    elevation: 5,
                    radius: 75,
                  )
```

**Comment by ch-muhammad-adil** [comment]
Thanks Allan for reporting that, let me give a try to your code.

**Comment by ch-muhammad-adil** [comment]
@AllanSullivan  just try this code please 



               CircularProfileAvatar(
                  null,
                  child: Icon(
                    Icons.account_circle,
                    size: 150,
                  ),
                  borderColor: Colors.black,
                  borderWidth: 0,
                  elevation: 0,
                  radius: 75,
                )


What you are doing here, you have set `size` of your Icon to 200, which should be below `radius`+`border` of the `CircularProfileAvatar` widget. 

So I have given you a sample without adding any border and elevation so you can know where things are wrong. Please try to use 145 `size` of Icon.

**Comment by ch-muhammad-adil** [comment]
So for your case this code should work fine 

      CircularProfileAvatar(
                null,
                child: Icon(
                  Icons.account_circle,
                  size: 145,
                ),
                borderColor: Colors.black,
                borderWidth: 3,
                elevation: 5,
                radius: 75,
              )

**Comment by ch-muhammad-adil** [comment]
I am closing this now I hope this is what you are looking for :) .
